# Generated by Django 3.2.5 on 2021-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
        migrations.AddField(
            model_name='certify',
            name='book_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
