# Generated by Django 3.2.5 on 2021-07-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210720_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certify',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='health',
            name='created',
            field=models.DateField(),
        ),
    ]
